defaults:
  - env: dSprites
  - agent: CriticalHMM
  - _self_

checkpoint:
  directory: "${oc.env:DATA_DIRECTORY}/${env.name}/${agent.name}/${seed}/model.pt"
  frequency: 100

images:
  shape: ${tuple:1,64,64}

debug_mode: true
n_training_steps: 10000000
buffer_start_size: 50
batch_size: 50
seed: 42
nb_envs: 5
