name: cahmm

defaults:
  - encoder: convolutional64adversarial
  - decoder: convolutional64
  - transition: linearRelu3x100
  - critic: linearReluDropout4x100
  - action_selection: epsilonGreedy

_target_: agents.CAHMM.CAHMM

# Miscellaneous
n_states: 10
n_actions: ${env.n_actions}
vfe_lr: 0.0001
discriminator_lr: 0.0001
efe_lr: 0.001
discount_factor: 0.95
n_steps_between_synchro: 10
queue_capacity: 50000
tensorboard_dir: "${oc.env:DATA_DIRECTORY}/runs/${agent.name}_${env.name}_${seed}"
g_value: "efe"
discriminator_threshold: 0.9

# Beta scheduling
beta: 1.0
beta_starting_step: 0
beta_rate: 0.0
n_steps_beta_reset: 10000000000
