name: critic

defaults:
  - critic: linearRelu4x100

_target_: agents.Critic.Critic

# Miscellaneous
n_states: 113
efe_lr: 0.001
discount_factor: 0.95
n_steps_between_synchro: 10
queue_capacity: 50000
tensorboard_dir: "${oc.env:DATA_DIRECTORY}/runs/Critic_${env.name}_${seed}"
action_selection: "epsilon_greedy"
